#!/usr/bin/env bash


source /opt/rh/rh-python34/enable

start() {
    pylogchop start
}

stop() {
    pylogchop quit
}

reload() {
    pylogchop reload
}


case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        reload)
                reload
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac

exit 0